### ISSUE TITLE
hxnet telnet client

### ISSUE THREAD

**Issue by R3D9477** [sh-dave/hxnet-examples#1]
Hi. How I can write simple console-based telnet client?
I tried to made a simple telnet client.

TelnetClient.hx:
```
package;

#if cpp
	import cpp.vm.Thread;
#elseif neko
	import neko.vm.Thread;
#end

import hxnet.interfaces.Connection;
import hxnet.protocols.Telnet;
import hxnet.tcp.Client;

class TelnetClient extends Telnet
{
	static public function main() {
		var protocol = new TelnetClient();
		
		var client = new Client();
		client.protocol = protocol;
		client.blocking = false;
		client.connect("XXX.XXX.XXX.XXX", 23);
		
		var clientThread = Thread.create(function() while (client != null) client.update());
		
		var cmd:String;
		
		while ((cmd = Sys.stdin().readLine()) != "exit")
			protocol.writeLine(cmd);
		
		client.close();
		client = null;
	}
	
	override public function onConnect(cnx:Connection) {
		super.onConnect(cnx);
		trace("[connected to Server]");
	}
	
	override private function lineReceived (line:String) {
		trace('> $line');
	}
	
	override public function writeLine(data:String):Void {
		trace('< ${data}');
		super.writeLine(data);
	}
}
```

I already connected to server, but I can't receive responce from server.
At first I must write login, then password, and then i tried to write command "ls ~/" and get response. But I haven't messages from server.

Thanks.

**Comment by sh-dave** [comment]
hi, i justed tested a neko build of your code on my windows machine, and it's actually working.
The only change i made was to enable blocking, b/c neko would throw an exception otherwise.

```haxe
client.blocking = true;
client.connect('localhost', 23);
```

I used this as server: http://pwts.sourceforge.net

I created this repository only for samples. If you have problems with hxnet, you should better use the official libraries one at https://github.com/MattTuttle/hxnet. And i stopped using hxnet a couple of months ago, so i'm probably not of much help. I hope you get it sorted out though!

**Comment by R3D9477** [comment]
many thanks for help!
